[module]
  [module.hugoVersion]
    extended = true
    min = "0.141.0"
    max = ""
  [[module.mounts]]
    source = "dist/simple-datatables.js"
    target = "assets/js/modules/simple-datatables/simple-datatables.js"
  [[module.mounts]]
    source = "dist"
    target = "assets/scss"
    includeFiles = "simple-datatables.scss"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'i18n'
    target = 'i18n'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.imports]]
    path = "github.com/gethinode/mod-bootstrap"
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"

[params.modules.simple-datatables]
  integration = "optional"
  state = "async"
  localize = true

[params.modules.simple-datatables.csp]
  img-src = ["data:"]